name: run main.py

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * 1-5'  # Runs at 8:00 AM IST (2:30 AM UTC), Monday to Friday

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:

      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.9' # install the python version needed

      - name: List repo files
        run: ls -R

      - name: Send Email Notification via Python
        run: python applicationStartupMail.py

      - name: execute py script # run main.py
        run: python findStockLiveOnly.py


